module: VHCarrouselCollectionView
readme: README.md
author: Vidal HARA
author_url: https://github.com/vidalhara
github_url: https://github.com/vidalhara/VHCarrouselCollectionView
copyright: Copyright © 2022 Vidal HARA. VHCarrouselCollectionView released under MIT License.
output: Docs
theme: fullwidth
xcodebuild_arguments: [-project, Example/VHCarrouselExample.xcodeproj, -scheme, VHCarrouselExample, -sdk, iphoneos]
